ingestion-post-and-get-api-changes
datakaveri/iudx-resource-server pull request #384
Opened 2023-03-02 21:59 UTC by gopal-mahajan

- **API Server Changes**

- [ ] Changes done in registerAdapter method and publishAllAdapterForUser method

- **ManagmentApiImpl Changes**
- [ ] In registerAdapter method flow to create exchange has been refactored to cache call for given entities followed by insertion in postgres which is further followed by creation of exchange in dataBroker.
- [ ] In publishAllAdapterForUser call to dataBroker has been discontinued. Now data is been fetch from a call to postgres.

**Note** : ManagmentApiImplTest is commented as changes are yet to be made in that file.

2023-03-03 03:55 UTC, kailash requested changes

2023-03-03 03:55 UTC, kailash commented on src/main/resources/db/migration/V4_5__Create_ingestion_table.sql
> +CREATE TABLE IF NOT EXISTS ingestion
1. rename DB table name to `adaptors_details`.
2. add `created_at` and `modified_at` columns
3. insert `created_at` and `modified_at` columns through trigger on insert/update

2023-03-03 03:55 UTC, kailash commented on src/main/java/iudx/resource/server/apiserver/management/ManagementApiImpl.java
>    public Future<JsonObject> deleteAdapter(String adapterId, String userId,
Once Adapter is deleted from RMQ, is should also get deleted from the database.

2023-03-03 03:58 UTC, kailash commented on src/main/java/iudx/resource/server/apiserver/management/ManagementApiImpl.java
> +  public Future<JsonObject> publishAllAdapterForUser(JsonObject request, PostgresService postgresService) {
The method name `getAllAdapterDetailsForUser` makes more sense than `publishAllAdapterForUser`. Change method name to `getAllAdapterDetailsForUser`

2023-03-06 20:37 UTC, gopal-mahajan commented
![image](https://user-images.githubusercontent.com/60537181/223224959-d64eb417-6970-4620-a480-f269afa18feb.png)

Screenshot of code coverage.

2023-03-08 04:46 UTC, kailash commented
retest this please

2023-03-08 04:52 UTC, kailash commented
retest this please

2023-03-08 05:24 UTC, kailash commented
retest this please

2023-03-08 06:48 UTC, merged